# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types:
      - published
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Publish
      run: |
        dotnet publish .\SEGA835Lib\SEGA835Lib.csproj --configuration Release /p:PublishProfile=.\SEGA835Lib\Properties\PublishProfiles\Net6.pubxml -f:net6.0-windows7
        dotnet publish .\SEGA835Lib\SEGA835Lib.csproj --configuration Release /p:PublishProfile=.\SEGA835Lib\Properties\PublishProfiles\Net8.pubxml -f:net8.0-windows
        dotnet publish .\SEGA835Lib\SEGA835Lib.csproj --configuration Release /p:PublishProfile=.\SEGA835Lib\Properties\PublishProfiles\Net10.pubxml -f:net10.0-windows
        dotnet publish .\SEGA835Lib\SEGA835Lib.csproj --configuration Release /p:PublishProfile=.\SEGA835Lib\Properties\PublishProfiles\NetStandard20.pubxml -f:netstandard2.0
        dotnet publish .\SEGA835Lib\SEGA835Lib.csproj --configuration Release /p:PublishProfile=.\SEGA835Lib\Properties\PublishProfiles\NetStandard21.pubxml -f:netstandard2.1
        dotnet publish .\SEGA835Lib\SEGA835Lib.csproj --configuration Release /p:PublishProfile=.\SEGA835Lib\Properties\PublishProfiles\NetStandard21.pubxml -f:netstandard2.1
        dotnet publish .\SEGA835Lib\SEGA835Lib.csproj --configuration Release /p:PublishProfile=.\SEGA835Lib\Properties\PublishProfiles\Net35.pubxml -f:net35
        dotnet publish .\SEGA835Lib\SEGA835Lib.csproj --configuration Release /p:PublishProfile=.\SEGA835Lib\Properties\PublishProfiles\Net481.pubxml -f:net481
        dotnet publish .\SEGA835Cmd\SEGA835Cmd.csproj --configuration Release /p:PublishProfile=.\SEGA835Cmd\Properties\PublishProfiles\Sega835Cmd.pubxml
    - name: Upload Lib NET 6
      uses: actions/upload-artifact@v7
      with:
        name: Sega835Lib-net6-latest
        path: SEGA835Lib/publish/net6
        if-no-files-found: error
        overwrite: true
    - name: Upload Lib NET 8
      uses: actions/upload-artifact@v7
      with:
        name: Sega835Lib-net8-latest
        path: SEGA835Lib/publish/net8
        if-no-files-found: error
        overwrite: true
    - name: Upload Lib NET 10
      uses: actions/upload-artifact@v7
      with:
        name: Sega835Lib-net10-latest
        path: SEGA835Lib/publish/net8
        if-no-files-found: error
        overwrite: true
    - name: Upload Lib NET Standard 2.0
      uses: actions/upload-artifact@v7
      with:
        name: Sega835Lib-netstandard2.0-latest
        path: SEGA835Lib/publish/netstandard20
        if-no-files-found: error
        overwrite: true
    - name: Upload Lib NET Standard 2.1
      uses: actions/upload-artifact@v7
      with:
        name: Sega835Lib-netstandard2.1-latest
        path: SEGA835Lib/publish/netstandard21
        if-no-files-found: error
        overwrite: true
    - name: Upload Lib NET Framework 3.5
      uses: actions/upload-artifact@v7
      with:
        name: Sega835Lib-netframework35
        path: SEGA835Lib/publish/net35
        if-no-files-found: error
        overwrite: true
    - name: Upload Lib NET Framework 4.8.1
      uses: actions/upload-artifact@v7
      with:
        name: Sega835Lib-netframework481
        path: SEGA835Lib/publish/net481
        if-no-files-found: error
        overwrite: true
    - name: Upload Cmd
      uses: actions/upload-artifact@v7
      with:
        name: Sega835Cmd-latest
        path: SEGA835Cmd/publish
        if-no-files-found: error
        overwrite: true
    - name: Upload Lib nupkg
      uses: actions/upload-artifact@v7
      with:
        name: Sega835Lib.nupkg
        path: SEGA835Lib/bin/Release/*.nupkg
        if-no-files-found: error
        overwrite: true
              
  validate_nuget:
    runs-on: windows-latest
    needs: [ build ]
    steps:
      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      # Download the NuGet package created in the previous job
      - uses: actions/download-artifact@v8
        with:
          name: Sega835Lib.nupkg
          path: ${{ env.NuGetDirectory }}

      - name: Install nuget validator
        run: dotnet tool update Meziantou.Framework.NuGetPackageValidation.Tool --global

      # Validate metadata and content of the NuGet package
      # https://www.nuget.org/packages/Meziantou.Framework.NuGetPackageValidation.Tool#readme-body-tab
      # If some rules are not applicable, you can disable them
      # using the --excluded-rules or --excluded-rule-ids option
      - name: Validate package
        run: meziantou.validate-nuget-package (Get-ChildItem "${{ env.NuGetDirectory }}/*.nupkg") --excluded-rules Symbols

  run_test:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
    - name: Run tests
      run: dotnet test --configuration Release --verbosity normal --logger trx 835TestsMaybeLess
    - name: Upload Test Result Files
      uses: actions/upload-artifact@v7
      with:
        name: test-results
        path: ${{ github.workspace }}/**/TestResults/**/*
        retention-days: 5
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: always()
      with:
        files: "${{ github.workspace }}/**/*.trx"



  deploy:
    permissions:
        contents: write
    runs-on: windows-latest
    needs: [ validate_nuget, run_test ]
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: ${{ env.NuGetDirectory }}
          merge-multiple: true
          skip-decompress: false
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
      - name: Publish NuGet package
        run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
      - name: Add binaries to release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ${{ env.NuGetDirectory }}/*
